version: '3.4'

networks:
    main-network:
services:
    go-service:
        build:
            context: ./
            dockerfile: dockerfile.dockerfile
        container_name: go-service
        restart: unless-stopped
        working_dir: /var/www/app
        expose:
            - 8080
        environment:
            DB_PASSWORD: eboyVwwtr3gt42S
            DB_HOST: db-service
            APP_NAME: EXX SERVICE223
            DB_PORT: 3306
        volumes:
            - ./:/var/www/app
        networks:
            - main-network
        depends_on:
            - db-service
    db-service:
        image: mysql:5.7.22
        container_name: db-service
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: go_demo
            MYSQL_ROOT_PASSWORD: eboyVwwtr3gt42S
            MYSQL_PASSWORD: eboyVwwtr3gt42S
            MYSQL_USER: eboy
        networks:
            - main-network
        expose:
            - 3306
        volumes:
            - ./docker/mysql-data2:/var/lib/mysql
    nginx-service:
        image: nginx:1.17-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/app
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - main-network
        depends_on:
            - go-service
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - main-network
volumes:
    nginx:
    mysql-data:
    app:
